apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ratelimit
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: ambassador-ratelimit
    spec:
      volumes:
      - name: config
        configMap:
          name: ratelimit-config
          items:
          - key: config_ip.yaml
            path: config.yaml
      containers:
      - args:
        - /bin/ratelimit
        env:
        - name: LOG_LEVEL
          value: debug
        - name: REDIS_SOCKET_TYPE
          value: tcp
        - name: REDIS_URL
          value: redis:6379
        - name: RUNTIME_ROOT
          value: /data
        - name: RUNTIME_SUBDIRECTORY
          value: ratelimit
        - name: USE_STATSD
          value: "false"
        - name: GRPC_PORT
          value: "8081"
        - name: DEBUG_PORT
          value: "6070"
        image: lyft-ratelimit
        name: ratelimit
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          - name: grpc
            containerPort: 8081
            protocol: TCP
          - name: debug
            containerPort: 6070
            protocol: TCP 
        resources:
          limits:
            cpu: 1
            memory: 400Mi
          requests:
            cpu: 200m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: data/ratelimit/config/config.yaml
          subPath: config.yaml
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 3
      restartPolicy: Always
