apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: redis
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: redis
    spec:
      containers:
      - image: redis:alpine
        name: redis
        ports:
        - containerPort: 6379
      restartPolicy: Always
status: {}
